async (page) => {
 await page.reload();await page.waitForFunction(()=>!!window.__mars);
 const base={version:1,seed:1410513364,money:80,levels:{drill:2,fuel:1,cargo:1,hull:1,engine:1},fuel:140,hull:100,cargo:{copper:0,iron:0,silver:0,gold:0,diamond:0},maxDepth:0,artifact:false,x:980,y:-22,destroyed:[],discovered:[]};
 const destroyed=[];for(let y=0;y<31;y++)for(let x=0;x<48;x++)destroyed.push(`${x},${y}`);
 const fixture={...base,x:980,y:-22,money:300,fuel:30,hull:40,cargo:{copper:0,iron:0,silver:3,gold:2,diamond:0},destroyed};
 await page.evaluate(s=>localStorage.setItem('mars-miner.v1',JSON.stringify(s)),fixture);
 await page.reload();await page.getByRole('button',{name:'CONTINUE EXPEDITION ↗'}).waitFor();await page.keyboard.press('Space');
 await page.waitForTimeout(10000);
 const idle=await page.evaluate(()=>window.__mars);
 if(!idle.docked||idle.y!==-22||idle.hull!==40||idle.fuel!==30||idle.destroyed.length!==destroyed.length)throw Error('Old-save safe docking failed');
 await page.setViewportSize({width:960,height:720});await page.waitForTimeout(800);
 await page.screenshot({path:'output/playwright/ux-surface-960.png'});
 await page.keyboard.press('e');await page.keyboard.press('Space');
 if((await page.evaluate(()=>window.__mars.money))!==675)throw Error('Space sale failed');
 await page.getByRole('button',{name:'Service',exact:true}).click();
 const cost=Math.ceil((140-30)*.3)+Math.ceil((100-40)*.45);
 await page.getByRole('button',{name:`REFUEL + REPAIR $${cost}`,exact:true}).click();
 const serviced=await page.evaluate(()=>window.__mars);
 if(serviced.money!==675-cost||serviced.fuel!==140||serviced.hull!==100)throw Error('Combined service failed');
 await page.getByRole('button',{name:'Sell ore',exact:true}).click();
 if(!(await page.locator('.ore-list').innerText()).includes('× 3'))throw Error('Receipt was lost');
 await page.getByRole('button',{name:'Upgrades',exact:true}).click();
 await page.screenshot({path:'output/playwright/ux-workshop-960.png'});
 await page.setViewportSize({width:960,height:560});
 await page.getByRole('button',{name:'$160 ↑',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'output/playwright/ux-short-workshop.png'});
 await page.reload();await page.getByRole('button',{name:'CONTINUE EXPEDITION ↗'}).waitFor();
 const full={...base,x:980,y:-22,seed:1410513364,fuel:140,hull:100,destroyed:[],cargo:{copper:16,iron:0,silver:0,gold:0,diamond:0}};
 await page.evaluate(s=>localStorage.setItem('mars-miner.v1',JSON.stringify(s)),full);
 await page.reload();await page.getByRole('button',{name:'CONTINUE EXPEDITION ↗'}).click();
 await page.setViewportSize({width:1440,height:960});await page.keyboard.down('s');await page.waitForTimeout(400);
 const warning=await page.locator('#drill-target').innerText();
 const before=await page.evaluate(()=>window.__mars);
 if(!warning.includes('ORE WILL BE LOST')||before.destroyed.length)throw Error('Missing pre-cut safeguard');
 await page.screenshot({path:'output/playwright/ux-cargo-warning.png'});
 await page.keyboard.up('s');await page.waitForTimeout(100);
 if((await page.evaluate(()=>window.__mars.destroyed.length))!==0)throw Error('Canceled cut destroyed ore');
 await page.keyboard.down('s');await page.waitForTimeout(1450);await page.keyboard.up('s');await page.keyboard.press('Escape');
 const discarded=await page.evaluate(()=>window.__mars);
 if(!discarded.destroyed.includes('24,0')||discarded.cargo.copper!==16)throw Error('Deliberate escape cut failed');
 return {idle:{y:idle.y,hull:idle.hull,fuel:idle.fuel,docked:idle.docked},serviced:{money:serviced.money,hull:serviced.hull,fuel:serviced.fuel},warning,discarded:discarded.destroyed};
}
